<a href="https://colab.research.google.com/github/armandoordonez/mlops/blob/main/MLOps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#!pip install pycaret

In [ ]:
# load dataset
from pycaret.datasets import get_data
insurance = get_data('insurance')
type(insurance)

df = insurance[['age','bmi','children','charges']]

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
# init environment
from pycaret.regression import setup,create_model,save_model,get_config

r1 = setup(df, target = 'charges', session_id = 123,
           normalize = True,
           polynomial_features = True)

# train a model
lr = create_model('lr')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [ ]:

import numpy as np
import pandas as pd
from pycaret.regression import predict_model

cols =cols = ['age',  'bmi', 'children']
final = np.array(['36', '27.900', '3'])
data_unseen = pd.DataFrame([final], columns = cols)

prediction = predict_model(lr, data=data_unseen, round = 0)
print("***************",prediction)
prediction = int(prediction.prediction_label[0])

***************   age     bmi children  prediction_label
0  36  27.900        3      12077.449961

In [ ]:
from pycaret.regression import get_config
configuration = get_config()
configuration

{'USI',
 'X',
 'X_test',
 'X_test_transformed',
 'X_train',
 'X_train_transformed',
 'X_transformed',
 '_available_plots',
 '_ml_usecase',
 'data',
 'dataset',
 'dataset_transformed',
 'exp_id',
 'exp_name_log',
 'fold_generator',
 'fold_groups_param',
 'fold_shuffle_param',
 'gpu_n_jobs_param',
 'gpu_param',
 'html_param',
 'idx',
 'is_multiclass',
 'log_plots_param',
 'logging_param',
 'memory',
 'n_jobs_param',
 'pipeline',
 'seed',
 'target_param',
 'test',
 'test_transformed',
 'train',
 'train_transformed',
 'transform_target_param',
 'variable_and_property_keys',
 'variables',
 'y',
 'y_test',
 'y_test_transformed',
 'y_train',
 'y_train_transformed',
 'y_transformed'}

In [ ]:
x_4_train = get_config("X_train")

x_4_train_transf = get_config("X_train_transformed")

In [ ]:
x_4_train.head()

     age        bmi  children
300   36  27.549999         3
904   60  35.099998         0
670   30  31.570000         3
617   49  25.600000         2
373   26  32.900002         2

In [ ]:
x_4_train_transf.head()

,age,bmi,children,age^2,age bmi,age children,bmi^2,bmi children,children^2
300,-0.220584,-0.521212,1.577352,-0.383008,-0.415391,1.260325,-0.569778,1.274050,1.408662
904,1.483407,0.757039,-0.879223,1.661025,1.735095,-0.829425,0.689659,-0.852059,-0.586055
670,-0.646582,0.159393,1.577352,-0.734326,-0.501665,0.912033,0.063025,1.584285,1.408662
617,0.702411,-0.851356,0.758494,0.597312,0.091446,1.066829,-0.845738,0.465023,0.300486
373,-0.930581,0.384569,0.758494,-0.933051,-0.678652,0.176751,0.291332,0.840597,0.300486

In [ ]:
# save pipeline/model
save_model(lr, model_name = 'short_deployment_28042020')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=FastMemory(location=/tmp/joblib),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['age', 'bmi', 'children'],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=[],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('polynomial_features',
                  TransformerWrapper(transformer=PolynomialFeatures(include_bias=False))),
                 ('normalize', TransformerWrapper(transformer=StandardScaler())),
                 ('trained_model', LinearRegression(n_jobs=-1))]),
 'short_deployment_28042020.pkl')